set windows-powershell := true

CONFIG_DIR := parent_directory(justfile_directory())
SCRIPTS_DIR := join(CONFIG_DIR,"my-scripts")

restart:
	komorebic stop ; true
	sleep 1
	cmd /c "start /b komorebi"
	sleep 1
	just configure

command +ARGS:
	komorebic {{ARGS}}

WORKSPACE_PADDING := "0"
CONTAINER_PADDING := "3"
configure:
	komorebic container-padding 0 0 {{CONTAINER_PADDING}}
	komorebic workspace-padding 0 0 {{WORKSPACE_PADDING}}

	komorebic manage-rule exe alacritty.exe
	komorebic float-rule class "Launchy options"
	komorebic float-rule class SunAwtDialog
	komorebic float-rule class TWizardForm
	komorebic float-rule exe flux.exe

	komorebic change-layout ultrawide-vertical-stack

	komorebic identify-tray-application exe Battle.net.exe
	komorebic identify-border-overflow exe Battle.net.exe

	komorebic identify-tray-application exe Element.exe

	komorebic identify-tray-application exe Discord.exe
	komorebic identify-border-overflow exe Discord.exe

	komorebic identify-tray-application exe Todoist.exe
	komorebic identify-border-overflow exe Todoist.exe


	komorebic.exe focus-follows-mouse enable
	komorebic retile

help:
	komorebic --help | just -f {{SCRIPTS_DIR}}/justfile wm-show
