set windows-powershell := true

CONFIG_DIR := parent_directory(justfile_directory())
SCRIPTS_DIR := join(CONFIG_DIR,"my-scripts")
KMONAD_DIR := join(CONFIG_DIR,"kmonad")

kill:
	eledo taskkill /IM kmonad.exe /F

restart:
	eledo just kill ; eledo just start

start:
	eledo kmonad.exe {{ join(KMONAD_DIR, "config.kbd") }} -c -l debug
