set shell := ["cmd.exe", "/c"]
# set shell := ["powershell.exe", "-c"]

# PROG_FILES_UNIX_PATH := `cygpath -u "$PROGRAMFILES"`
# ST_EXE_PATH := "$PROG_FILES_UNIX_PATH/SyncTrayzor/syncthing.exe"
# ST_SYNC_DIR := `cygpath -u $:

JUST_DIR := "{{justfile_directory()}}"
KOMOREBI_DIR := "{{JUST_DIR}}/../komorebi"
KMONADC_DIR := "{{JUST_DIR}}/../kmonad"

terminal:
	alacritty

web-browser:
	firefox

file-explorer:
	start ~

wm-restart:
	just {{KOMOREBI_DIR}}/restart

wm-command +ARGS:
	just {{KOMOREBI_DIR}}/command {{ARGS}}

wm-configure:
	just {{KOMOREBI_DIR}}/configure

wm-help:
	komorebic --help | just wm-show

wm-show:
	#!/usr/bin/env arturo
	a: []
	loop.forever ['a] [] [try? [a: a ++ input ""] else [break]]
	webview join.with:"<br>" a

quick-edit:
	alacritty.exe -o window.decorations=none -e micro
