set shell := ["cmd.exe", "/c"]
# set shell := ["powershell.exe", "-c"]

# PROG_FILES_UNIX_PATH := `cygpath -u "$PROGRAMFILES"`
# ST_EXE_PATH := "$PROG_FILES_UNIX_PATH/SyncTrayzor/syncthing.exe"
# ST_SYNC_DIR := `cygpath -u $:

CONFIG_DIR := parent_directory(justfile_directory())
SCRIPTS_DIR := justfile_directory()
KMONAD_DIR := join(CONFIG_DIR,"kmonad")
KOMOREBI_DIR := join(CONFIG_DIR,"komorebi")

terminal:
	alacritty

web-browser:
	firefox

file-explorer:
	start ~

wm +ARGS:
	just -f {{KOMOREBI_DIR}}/justfile {{ARGS}}

kmonad +ARGS:
	just -f {{KMONAD_DIR}}/justfile {{ARGS}}

wm-help:
	komorebic --help | just wm-show

wm-show:
	#!/usr/bin/env arturo
	a: []
	loop.forever ['a] [] [try? [a: a ++ input ""] else [break]]
	webview join.with:"<br>" a

quick-edit:
	alacritty.exe -o window.decorations=none -e micro
