(define split 0.55)
(define GAP 6)

;; (define (add-gap num) (+ num GAP))
(define (add-gap num) (- num GAP))
(define (layout:rows n x y w h)
  (letrec ((height (/ h n))
           (rows (lambda (n)
                   (if (eq? n 0)
                       '()
                       (let ((Y (- (+ y h) (* n height))))
                         (append (list (list x Y (add-gap w) (add-gap height)))
                                 (rows (- n 1))))))))
    (rows n)))

(define (layout:split n x y w h)
  (if (eq? n 1)
      (list (list x y (add-gap w) (add-gap h)))
      (letrec* ((left (* split w))
                (right (- w left)))
        (append (list (list x y (add-gap left) (add-gap h)))
                (layout:rows (- n 1) (+ x left) y right h)))))

(install-handler 'layout-demand (lambda (view-count width height tags output)
                                  (layout:split view-count GAP GAP width height)))
